# Generated by Django 5.2.9 on 2025-12-06 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='Место')),
                ('time', models.TimeField(verbose_name='Время')),
                ('action', models.CharField(max_length=255, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, help_text='Если включено — это приятная (вознаграждающая) привычка', verbose_name='Приятная привычка')),
                ('periodicity', models.PositiveSmallIntegerField(default=1, help_text='Как часто выполнять привычку (1–7 дней)', verbose_name='Периодичность (в днях)')),
                ('reward', models.CharField(blank=True, help_text='Текстовое вознаграждение (если не используем приятную привычку)', max_length=255, null=True, verbose_name='Вознаграждение')),
                ('execution_time', models.PositiveSmallIntegerField(default=60, help_text='Не больше 120 секунд', verbose_name='Время на выполнение (сек.)')),
                ('is_public', models.BooleanField(default=False, help_text='Если включено — привычка видна другим пользователям', verbose_name='Публичная привычка')),
                ('last_reminder', models.DateField(blank=True, null=True, verbose_name='Дата последнего напоминания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('related_habit', models.ForeignKey(blank=True, help_text='Приятная привычка, которая идёт как награда', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_for', to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ('-created_at',),
            },
        ),
    ]
